apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-cont
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hey folks
          restartPolicy: OnFailure
