apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    name: raj
  ports:
    - name: nodeport
      protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 80
