apiVersion: v1
kind: Pod
metadata:
  name: pod-resource-mgmt
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-worker02
  containers:
  - name: my-cont
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 200m
        memory: 20Mi
      limits:
        cpu: 500m
        memory: 64Mi
