apiVersion: v1
kind: Pod
metadata:
  name: pv-pvc-pod-test
spec:
  containers:
    - name: my-cont
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name: my-volume
          mountPath: /data/www/
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: persistent-volume-claim
