apiVersion: v1
kind: ReplicationController
metadata:
  name: replica-cont
spec:
  replicas: 2
  selector: 
    env: practice
  template:
    metadata:
      name: whatever
      labels:
        env: practice
    spec:
      containers:
        - name: prac-con
          image: nginx
          ports:
          - containerPort: 80
